# Generated by Django 4.2.21 on 2025-12-08 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='allow_nominations',
            field=models.BooleanField(default=True, help_text='Si está en False, el premio está cerrado y no admite nuevas nominaciones.'),
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazana', models.TextField(verbose_name='Hazaña de la nominación')),
                ('is_active', models.BooleanField(default=True, help_text='Si está en False, esta nominación no se mostrará en el front.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominaciones', to='awards.award')),
                ('nominado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('nominado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominaciones_hechas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nominación',
                'verbose_name_plural': 'Nominaciones',
            },
        ),
        migrations.AddConstraint(
            model_name='nomination',
            constraint=models.UniqueConstraint(fields=('award', 'nominado', 'nominado_por'), name='unique_nomination_per_award_and_user_pair'),
        ),
    ]
