# Generated by Django 4.2.21 on 2025-12-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0005_remove_vote_unique_vote_per_award_per_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_active_vote_per_award_and_user',
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('award', 'voter', 'nomination'), name='unique_vote_per_award_voter_nomination'),
        ),
    ]
