# Generated by Django 4.2.21 on 2025-12-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0006_remove_vote_unique_active_vote_per_award_and_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_vote_per_award_voter_nomination',
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('award', 'voter'), name='unique_active_vote_per_award_and_user'),
        ),
    ]
