# Generated by Django 4.2.21 on 2025-12-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0008_award_allow_voting_award_show_results_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='allow_voting',
            field=models.BooleanField(default=True, help_text='Si está en False, no se puede votar este premio.'),
        ),
    ]
