# Generated by Django 5.1.15 on 2025-12-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0009_alter_award_allow_voting'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='allow_pair_nominations',
            field=models.BooleanField(default=False, help_text='Si está en True, este premio permite nominar a dos integrantes juntos.'),
        ),
    ]
