# Generated by Django 5.1.15 on 2025-12-13 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0010_award_allow_pair_nominations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='nominado_secundario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nominaciones_recibidas_como_pareja', to=settings.AUTH_USER_MODEL),
        ),
    ]
