# Generated by Django 5.1.15 on 2025-12-14 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0011_nomination_nominado_secundario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='nomination',
            name='unique_nomination_per_award_and_user_pair',
        ),
        migrations.AddField(
            model_name='award',
            name='award_type',
            field=models.CharField(choices=[('people', 'Personas'), ('clip', 'Clip del Año')], default='people', help_text='people = premio normal (1 o 2 integrantes). clip = candidatos son clips con N participantes.', max_length=20),
        ),
        migrations.AddField(
            model_name='nomination',
            name='clip_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='nomination',
            name='clip_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='nomination',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='participaciones_en_nominaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='award',
            name='allow_nominations',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='allow_voting',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='show_results',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
