# Generated by Django 5.1.15 on 2025-12-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0012_remove_nomination_unique_nomination_per_award_and_user_pair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardsuggestion',
            name='award_type',
            field=models.CharField(choices=[('people', 'Personas'), ('clip', 'Clip / Vídeo')], default='people', max_length=20),
        ),
        migrations.AddField(
            model_name='awardsuggestion',
            name='max_participants',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Solo si nomination_mode='multi'. Ej: 4.", null=True),
        ),
        migrations.AddField(
            model_name='awardsuggestion',
            name='nomination_mode',
            field=models.CharField(choices=[('single', '1 participante'), ('pair', '2 participantes'), ('multi', 'Varios (3+)')], default='single', help_text='Cuántos participantes puede tener cada candidato (1 / 2 / varios).', max_length=20),
        ),
    ]
